# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazybrew < Formula
  desc "A lazy TUI for Homebrew"
  homepage "https://github.com/zh1C/lazybrew"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zh1C/lazybrew/releases/download/v0.0.1/lazybrew_0.0.1_darwin_amd64.tar.gz"
      sha256 "74f3cebf704f431651c3d7c3b73d752ac3a95f9fd95152530ff849c5041c7c6c"

      define_method(:install) do
        bin.install "lazybrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zh1C/lazybrew/releases/download/v0.0.1/lazybrew_0.0.1_darwin_arm64.tar.gz"
      sha256 "865e94690322f044601a580dde5b4de816cb287782355ca8445ebb8c08e65167"

      define_method(:install) do
        bin.install "lazybrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zh1C/lazybrew/releases/download/v0.0.1/lazybrew_0.0.1_linux_amd64.tar.gz"
      sha256 "a15c851edb0a53f65e89dcbe500633e3126b08625d1fe79ad0d1364b11cb57ca"
      define_method(:install) do
        bin.install "lazybrew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zh1C/lazybrew/releases/download/v0.0.1/lazybrew_0.0.1_linux_arm64.tar.gz"
      sha256 "4eeb64e36004ba6c716a05a0c9649911c512d9c57e53482eb76d174018b941c1"
      define_method(:install) do
        bin.install "lazybrew"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazybrew --version", 2)
  end
end
