# typed: false
# frozen_string_literal: true

# This file is auto-generated by GoReleaser. DO NOT EDIT.
class Lazybrew < Formula
  desc "A lazy TUI for Homebrew"
  homepage "https://github.com/zh1C/lazybrew"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/zh1C/lazybrew/releases/download/v0.1.0/lazybrew_0.1.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/zh1C/lazybrew/releases/download/v0.1.0/lazybrew_0.1.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zh1C/lazybrew/releases/download/v0.1.0/lazybrew_0.1.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end

    on_arm do
      url "https://github.com/zh1C/lazybrew/releases/download/v0.1.0/lazybrew_0.1.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "lazybrew"
  end
end
